### ISSUE TITLE
api customer/wallet/beneficiaries

### ISSUE THREAD

**Issue by benoptimus** [williamsko/money-transactions-platform#12]
{
     "address": "Dakar",
     "beneficiaries": [
         {
             "address": "Lome",
             "first_name": "Betty",
            "last_name": "Davis",
             "phone_number": "213-633-1514"
         }
     ],
     "created": "2020-06-15T22:03:20.561009",
     "id": 7,
    "identification_document_delivery_date": "2007-12-12",
     "identification_document_expiry_date": "2022-12-12",
     "identification_number": "EB012412312",
     "identification_type": "PP",
     "phone_number": "716-759-2189",
     "resource_uri": "/api/v1/customer/7/",
     "response_code": "000",
     "status": false,
     "updated": "2020-06-15T22:16:04.862580"
 }

pourrais tu peux ajouter les informations first name, last name du numero sur lequel on fait la recherche? j'en aurai besoin aussi.

**Comment by williamsko** [comment]
Hello boss les informations ont été rajoutées. 

`{'customer': {'first_name': customer.informations.first_name, 'last_name': customer.informations.last_name}`
