### ISSUE TITLE
ajout d'information agent à la connexion

### ISSUE THREAD

**Issue by benoptimus** [williamsko/money-transactions-platform#5]
dans le payload renvoyé pour la connexion il rajouté les infos personnelles de l'agent. Le nom, prenom, profile, solde iban, solde commission etc...

A la connexion comment on fait pour savoir si l'agent doit se connecter avec le token?

**Comment by williamsko** [comment]
Pour savoir que l'gent a besoin a besoin de se connecter avec un OTP il faut voir le champ `authentication_type` .

`authentication_type` a deux valeurs possibles pour le moment : 

```
DEFAULT = 'DEFAULT'
OTP = 'OTP
```'

**Comment by williamsko** [comment]
normalement pour les informations de l'agent tu as déjà : 
`username`
`first_name`
`last_name`
 
comme informations personnelles

**Comment by williamsko** [comment]
Je propose une autre aPI pour récupérer les informations : 

`solde`
`commission`
`date`

**Comment by benoptimus** [comment]
> Pour savoir que l'gent a besoin a besoin de se connecter avec un OTP il faut voir le champ `authentication_type` .
> 
> `authentication_type` a deux valeurs possibles pour le moment :
> 
> ```
> DEFAULT = 'DEFAULT'
> OTP = 'OTP'
> ```

au niveau du be? cela dit est que j'ai ll'info sur le payload retour apres login?

**Comment by benoptimus** [comment]
> Je propose une autre aPI pour récupérer les informations :
> 
> `solde`
> `commission`
> `date`

d'accord ça me va.

**Comment by benoptimus** [comment]
> normalement pour les informations de l'agent tu as déjà :
> `username`
> `first_name`
> `last_name`
> 
> comme informations personnelles

check le sample, ces informations n'y sont pas, et meme dans le payload après test.

**Comment by williamsko** [comment]
> > Pour savoir que l'gent a besoin a besoin de se connecter avec un OTP il faut voir le champ `authentication_type` .
> > `authentication_type` a deux valeurs possibles pour le moment :
> > ```
> > DEFAULT = 'DEFAULT'
> > OTP = 'OTP'
> > ```
> 
> au niveau du be? cela dit est que j'ai ll'info sur le payload retour apres login?

oui oui tu as l'information.

**Comment by benoptimus** [comment]
> > > Pour savoir que l'gent a besoin a besoin de se connecter avec un OTP il faut voir le champ `authentication_type` .
> > > `authentication_type` a deux valeurs possibles pour le moment :
> > > ```
> > > DEFAULT = 'DEFAULT'
> > > OTP = 'OTP'
> > > ```
> > 
> > 
> > au niveau du be? cela dit est que j'ai ll'info sur le payload retour apres login?
> 
> oui oui tu as l'information.

d'accord, je verifierais ça tout à l'heure

**Comment by williamsko** [comment]
> > > > Pour savoir que l'gent a besoin a besoin de se connecter avec un OTP il faut voir le champ `authentication_type` .
> > > > `authentication_type` a deux valeurs possibles pour le moment :
> > > > ```
> > > > DEFAULT = 'DEFAULT'
> > > > OTP = 'OTP'
> > > > ```
> > > 
> > > 
> > > au niveau du be? cela dit est que j'ai ll'info sur le payload retour apres login?
> > 
> > 
> > oui oui tu as l'information.
> 
> d'accord, je verifierais ça tout à l'heure




`{'address': 'Dakar Rue 10', **_'authentication_type': 'DEFAULT',_** 'code': '665493', 'created': '2020-05-21T17:58:06.198301', 'entity': {'account_number': 'SN669781267', 'address': '14B', 'brand_name': 'KBS', 'category': 'DISTRIBUTEUR', 'code': '667535', 'country': 'SN', 'email': 'monnamonsa@gmail.com', 'id': 2, 'parent': 1, 'phone_number': '0000000', 'status': True}, 'first_name': 'Test', 'id': 2, 'last_name': 'User', 'phone_number': '0000000', 'resource_uri': '/api/v1/entity/agent/2/', 'response_code': '000', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiY29kZSI6IjY2NTQ5MyIsImV4cCI6MTU5NDgyNTQyMn0.g7x67wzYY2SvEW0B9w4XkOC-NJVH2bdLYMRmFNarf6w', 'updated': '2020-05-21T17:58:17.547111'}`

**Comment by benoptimus** [comment]
le first_name et le last_name semble etre vide, un oublie d'insertion d'information peut etre?

**Comment by williamsko** [comment]
> le first_name et le last_name semble etre vide, un oublie d'insertion d'information peut etre?

Oui certainement.

**Comment by benoptimus** [comment]
> Je propose une autre aPI pour récupérer les informations :
> 
> `solde`
> `commission`
> `date`

donc je wait l'api pour ca, ce serait bient d'ajouter les 10 dernieres transactions par l'agent dans cette api.

**Comment by williamsko** [comment]
API : `/api/v1/transaction/agent/finance/situation`.
Tu mets dans le header de la requête le `token` de l'agent.

**Comment by williamsko** [comment]
API : `/api/v1/transaction/agent/stats.`
Tu mets dans le header de la requête le token de l'agent.

**Comment by benoptimus** [comment]
Intégré, j'ai eu des erreurs sur les deux urls :  
```
<title>RuntimeError
 at /api/v1/transaction/agent/stats</title>
<style type="text/css">
html * { padding:0; margin:0; }
body * { padding:10px 20px; }
body * * { padding:0; }
body { font:small sans-serif; backgroun
Error exception get agent stats Expecting value: line 1 column 1 (char 0 ..
```

J'ai fait un post, avec le token dans le header, sans données dans le body du post.

**Comment by williamsko** [comment]
Correction effectuée. Voici la réponse : `<Response [200]>
{u'commission': 0, u'response_code': u'000', u'balance': u'732690.00'}`

C'est dans la devise de l'entité déjà. Du coup tu peux la mettre.

**Comment by benoptimus** [comment]
> Correction effectuée. Voici la réponse : `<Response [200]> {u'commission': 0, u'response_code': u'000', u'balance': u'732690.00'}`
> 
> C'est dans la devise de l'entité déjà. Du coup tu peux la mettre.

je viens de faire un test ce matin j'ai toujours la meme erreur reportée dernierment pour les apis concernées c'est à dire : /api/v1/transaction/agent/stats et /api/v1/transaction/agent/finance/situation.

le token utilisé : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiY29kZSI6Ijk3NDYxOCIsImV4cCI6MTYwMjMyMDI3M30.DCFVZU_mO0N_7dinu6a-2ivyOP9R9f4Wr2vWMxoqXWk

**Comment by williamsko** [comment]
alors là on doit tester parce que je viens d'utiliser le token que tu viens de coller j'ai eu ceci comme résultat : 

`<Response [200]>
{u'commission': 0, u'response_code': u'000', u'balance': u'732690.00'}`

voici mon code  : 

`import requests
import json

# Agent Stat
token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiY29kZSI6Ijk3NDYxOCIsImV4cCI6MTYwMjMyMDI3M30.DCFVZU_mO0N_7dinu6a-2ivyOP9R9f4Wr2vWMxoqXWk'
headers = {'Content-Type': 'application/json',
           'Authorization': 'token {}'.format(token)}

url = 'http://217.69.6.52/api/v1/transaction/agent/finance/situation/'
response = requests.post(url, headers=headers)
print(response)
print(response.json())
`
