### ISSUE TITLE
api cash_to_cash 

### ISSUE THREAD

**Issue by benoptimus** [williamsko/money-transactions-platform#8]
Dans le playload renvoyer en reponse apres succes de la transaction, ajouter les informations concernant l'agent qui a effectue la transaction, l'url du logo du reseau selectionner pour le payement ainsi que les informations relatives à celui ci.

**Comment by benoptimus** [comment]
Il ya la date a laquelle a ete effectuee la transaction qu'il faut aussi ajouter.. prendre en compte l'ajout des informations demandées sur l'api pay aussi ( retrait cash to cash ).

waiting for feedback

**Comment by williamsko** [comment]
Tu peux retester stp ? Pour le logo du payeur je te propose de mettre celui de Monnamon pour le moment.

**Comment by benoptimus** [comment]
> Tu peux retester stp ? Pour le logo du payeur je te propose de mettre celui de Monnamon pour le moment.

voici le payload recu.

{
'agent':{
'code':'974618',
'entity':{
'brand_name':'CANYA WEST AFRICA'
},
'first_name':'',
'last_name':'',
'username':'test-agent'
},
'amount':'1000',
'date':'2020-06-25T12:28:22.497485',
'destination_content_object':{
'address':'dakr',
'first_name':'hello',
'last_name':'world',
'phone_number':'76 551 44 78'
},
'destination_country':'SN',
'motif_envoi':'0',
'paid_amount':'1500.000000000000',
'receipt_code':'107821229',
'response_code':'000',
'source_content_object':{
'address':'echo',
'first_name':'test',
'identification_document_delivery_date':'2020-06-12',
'identification_document_expiry_date':'2025-06-12',
'identification_number':'65374657465',
'identification_type':'PP',
'issuer_country':'SN',
'last_name':'test',
'phone_number':'78 014 89 60'
},
'source_country':'GW',
'source_revenu':'0',
'transaction_number':'7039029590',
'type':'CASH_TO_CASH'
}

les donnees manquantes et a ajouter:
    - les frais
    - le montant total 
    - le nom de l'agent ayant effectue l'envoi
    - le brand name de l'agence ayant effectue l'envoi
    - le logo de l'agence ayant effectue l'envoi
    - la date de l'operation
    - la source des revenues
    -  le taux applique sur la devise de reception par rapport a la devise d'envoi
    - devise de reception
    - le montant a payer en cette devise la 

 Ce sont ces informations la dont on a besoin pour construire le recu et qu'il ait le max d'information possible.

Tu peux faire le test pour voir a quoi il ressemble deja et les infos qui manquent.

**Comment by williamsko** [comment]
Tu peux vérifier stp
